asiakassovellus/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'asiakassovellus.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^manager/', include('manager.urls', namespace='manager'))
)

manager/urls.py
from django.conf.urls import patterns, url
from manager import views

urlpatterns = patterns('',
    # index page
    url(r'^index/$', views.IndexView, name='index'),
    # show all customers
    url(r'^showall/$', views.AllCustomersView, name='show_all'),
    # show info from specific customer
    url(r'^customer/(?P<pk>\d+)/$', views.CustomerView, name='customerinfo'),
    
    
    #===========================================================================
    # New customers and contacts
    #===========================================================================
    
    # show new customer view
    url(r'^customer/new/$', views.NewCustomerView, name='add_customer_form'),
    # show new contact view
    url(r'^contact/new/$', views.NewContactView, name='add_contact_form'),
    
    
    #===========================================================================
    # Data editing
    #===========================================================================
    
    # edit customer data
    url(r'^customer/(?P<pk>\d+)/edit/$', views.editCustomerView, name='edit_customer_form'),
    # edit contact data
    url(r'^customer/(?P<cus_id>\d+)/contact/(?P<con_id>\d+)/edit/$', views.editContactView, name='edit_contact_form'),
       
    
    #===========================================================================
    # removing
    #===========================================================================
    
    # remove customer
    url(r'^customer/(?P<cus_id>\d+)/remove/$', views.removeCustomer, name='customer_remove'),
    # remove contact
    url(r'^customer/(?P<cus_id>\d+)/contact/(?P<con_id>\d+)/remove/$', views.removeContact, name='contact_remove'),
    
    
    #===========================================================================
    # Login
    #===========================================================================
    
    # login at front page
    url(r'^$', views.LoginView, name='login'),
    # handle login
    url(r'^login/handle/$', views.handleLogin, name='login_handle'),
    # handle logout
    url(r'^logout/handle/$', views.handleLogout, name='logout_handle'),
)

manager/models.py
from django.db import models
from django.forms import ModelForm
from django.forms.widgets import TextInput, Textarea, Select

class Customer(models.Model):
    name = models.CharField(max_length=200)
    address = models.CharField(max_length=200)
    extrainfo = models.TextField()
    
    # better name
    def __unicode__(self):
        return self.name
    
class Contact(models.Model):
    customer = models.ForeignKey(Customer)
    name = models.CharField(max_length=200)
    lastname = models.CharField(max_length=200)
    job = models.CharField(max_length=200)
    phone = models.CharField(max_length=40)
    email = models.CharField(max_length=200)
    
    def __unicode__(self):
        return self.lastname + ' ' + self.name

class CustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = ('name', 'address', 'extrainfo')
        labels = {
            'name': ('Name'),
            'address': ('Address'),
            'extrainfo': ('Additional details'),
        }
        widgets = {
            'name': TextInput(attrs={'class': 'form-control'}),
            'address': TextInput(attrs={'class': 'form-control'}),
            'extrainfo': Textarea(attrs={'class': 'form-control'}),
        }
        
        
class ContactForm(ModelForm):
    class Meta:
        model = Contact
        fields = ('customer', 'name', 'lastname', 'job', 'phone', 'email')
        labels = {
            'customer': ('Customer'),
            'name': ('First name'),
            'lastname': ('Last name'),
            'job': ('Job description'),
            'phone': ('Phone'),
            'email': ('E-mail'),
            
        }
        widgets = {
            'customer': Select(attrs={'class': 'form-control'}),
            'name': TextInput(attrs={'class': 'form-control'}),
            'lastname': TextInput(attrs={'class': 'form-control'}),
            'job': TextInput(attrs={'class': 'form-control'}),
            'phone': TextInput(attrs={'class': 'form-control'}),
            'email': TextInput(attrs={'class': 'form-control'}),
        }
        

manager/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from manager.models import Customer, Contact, CustomerForm, ContactForm
from compiler.ast import TryExcept
from django.contrib.redirects.models import Redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.views.generic.base import TemplateView
from django.forms.models import modelformset_factory, modelform_factory
from django.forms import ModelForm, forms, formsets
from django.forms.formsets import formset_factory


# index page, currently empty

def IndexView(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    template_name = 'manager/index.html'
    return render(request,template_name)


 
#===============================================================================
# Customer related
#===============================================================================
def AllCustomersView(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    template_name = 'manager/allcustomers.html'   
    return render(request,template_name,{'all_customers': Customer.objects.all(), })
    
      
def CustomerView(request, pk):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    template_name = 'manager/customer.html'
    customer = get_object_or_404(Customer, id=pk)
    return render(request, template_name, {'customer': customer,})
    
def NewCustomerView(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    template_name = 'manager/newcustomer.html'
    
    # empty form
    customer_form = CustomerForm
    
    if request.method == 'POST':
        form = customer_form(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('manager:show_all'))
            
    else:
        form = customer_form
    
    return render(request, template_name, {'form': form, })
    
    


def editCustomerView(request, pk):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    template_name = 'manager/editcustomer.html'
    
    # get editable customer
    customer = get_object_or_404(Customer, id=pk)
    
    # empty form
    customer_form = CustomerForm

    if request.method == 'POST':
        form = customer_form(request.POST, instance = customer)
        if form.is_valid():
            form.save()
            
            return HttpResponseRedirect(reverse('manager:customerinfo', args=(customer.id,)))
    
    else:
        form = customer_form(instance = customer)
          
    return render(request, template_name, {'form': form, })


def removeCustomer(request, cus_id):  
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    customer = get_object_or_404(Customer, id=cus_id)
    customer.delete()
    
    return HttpResponseRedirect(reverse('manager:show_all'))      


#===============================================================================
# Contact related
#===============================================================================
def NewContactView(request):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    template_name = 'manager/newcontact.html'
    
    contact_form = ContactForm
    if request.method == 'POST':
        form = contact_form(request.POST)
        if form.is_valid():
            form.save()
            
            return HttpResponseRedirect(reverse('manager:show_all'))
    else:
        form = contact_form()
        
    return render(request, template_name, {'form': form, })


 
def editContactView(request, cus_id, con_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    template_name = 'manager/editcontact.html'
    
    contact = get_object_or_404(Contact, id=con_id)
    
    contact_form = ContactForm
    if request.method == 'POST':
        form = contact_form(request.POST, instance = contact)
        if form.is_valid():
            form.save()
            
            return HttpResponseRedirect(reverse('manager:customerinfo', args=(cus_id,)))
    else:
        form = contact_form(instance = contact)
        
    return render(request,template_name, {'form': form, 'contact': contact, })

     
def handleContactEdit(request, cus_id, con_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    customer = get_object_or_404(Customer, id=cus_id)
    contact = get_object_or_404(Contact, id=con_id)
    con_name = request.POST['name']
    con_lastname = request.POST['lastname']
    con_job = request.POST['job']
    con_phone = request.POST['phone']
    con_email = request.POST['email']
    
    if(con_name == "" or con_lastname == "" or con_job == "" or con_phone == "" or con_email == ""):
        return render(request, 'manager/editcontact.html', { 'error_message': 'Fill all fields!', 'customer': customer, 'contact': contact,})
    else:
        # save data
        contact.customer = customer
        contact.name = con_name
        contact.lastname = con_lastname
        contact.job = con_job
        contact.phone = con_phone
        contact.email = con_email
        
        contact.save()
        
        return HttpResponseRedirect(reverse('manager:customerinfo', args=(customer.id,)))

def removeContact(request, cus_id, con_id):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse('manager:login'))
    
    contact = get_object_or_404(Contact, id=con_id)
    contact.delete()
    
    return HttpResponseRedirect(reverse('manager:customerinfo', args=(cus_id,)))


#===============================================================================
# Login related
#===============================================================================
def LoginView(request):
    template_name = 'manager/login.html'
    return render(request, template_name)
    
def handleLogin(request):
    username = request.POST['username']
    password = request.POST['password']
    user = authenticate(username=username, password=password)
    if user is not None:
        if user.is_active:
            login(request, user)
            # user & passw ok
            return HttpResponseRedirect(reverse('manager:show_all'))
        else:
            # user or passw wrong
            return HttpResponseRedirect(reverse('manager:login'))
    else:
        # user or passw wrong
        return HttpResponseRedirect(reverse('manager:login'))
     
def handleLogout(request):
    logout(request)
    return HttpResponseRedirect(reverse('manager:login'))

    

manager/templates/manager/allcustomers.html

<!-- Basic HTML stuff (title, head, beginning of body) -->
{% include 'manager/structure/base_tpl_top.html' %}
<!-- Navigation -->
{% include 'manager/structure/navbar.html' %}

<div class="container">

	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">All customers</div>

		<!-- List group -->
		
			{% if all_customers %}
			<ul class="list-group">
				{% for customer in all_customers %}
				<li class="list-group-item"><a href="{% url 'manager:customerinfo' customer.id %}">{{ customer.name }}</a></li> 
				{% endfor %}
			</ul>
			{% endif %}

	</div>


</div>
{% include 'manager/structure/base_tpl_bottom.html' %}

manager/templates/manager/customer.html

<!-- Basic HTML stuff (title, head, beginning of body) -->
{% include 'manager/structure/base_tpl_top.html' %}
<!-- Navigation -->
{% include 'manager/structure/navbar.html' %}
<div class="container">

	<h2 id="customername">{{ customer.name }}</h2>
	<a href="{% url 'manager:edit_customer_form' customer.id %}">Edit</a>
	<p></p>
	<a href="{% url 'manager:customer_remove' customer.id %}" class="deletecustomer">Remove</a>

	<div class="panel panel-default">
		<div class="panel-heading">Address</div>
		<div class="panel-body">{{ customer.address }}</div>
	</div>
	<div class="panel panel-default">
		<!-- Default panel contents -->
		<div class="panel-heading">Contacts</div>

		<!-- Table -->
		{% if customer.contact_set.all.count < 1 %}
		<!-- IF no contacts -->
		<p>
			There is no contacts. <a href="{% url 'manager:add_contact_form' %}">Add one now</a>
		</p>
		{% else %}
		<table class="table">
			<tr>
				<th>First name</th>
				<th>Last name</th>
				<th>Job description</th>
				<th>Phone number</th>
				<th>E-mail</th>
				<th>Options</th>
			</tr>
			{% for contact in customer.contact_set.all %}

			<tr>
				<td>{{ contact.name }}</td>
				<td>{{ contact.lastname }}</td>
				<td>{{ contact.job }}</td>
				<td>{{ contact.phone }}</td>
				<td>{{ contact.email }}</td>
				<td><a href="{% url 'manager:edit_contact_form' customer.id contact.id %}"><span class="glyphicon glyphicon-refresh"></span></a><span>&nbsp&nbsp&nbsp&nbsp</span><a href="{% url 'manager:contact_remove' customer.id contact.id %}" class="deletelink"><span class="glyphicon glyphicon-remove"></span></a></td>
			</tr>
			{% endfor %}
		</table>
		{% endif %}
	</div>
	<div class="panel panel-default">
		<div class="panel-heading">Extra information</div>
		<div class="panel-body">{{ customer.extrainfo }}</div>
	</div>

</div>

{% include 'manager/structure/base_tpl_bottom.html' %} 



manager/templates/manager/editcontact.html

	<!-- Basic HTML stuff (title, head, beginning of body) -->
	{% include 'manager/structure/base_tpl_top.html' %}
	<!-- Navigation -->
	{% include 'manager/structure/navbar.html' %}
	
	
<div class="container">	
	<h1>Edit contact {{ contact.name }} {{ contact.lastname }}</h1>
	{% if error_message %} 
		<div class="alert alert-danger">{{ error_message }}</div>
	{% endif %}
	<form action="" method="post" role="form">
		{% csrf_token %}

		{% for field in form %}
			<div class="form-group">
				{{ field.errors }}
	            {{ field.label_tag }} {{ field }}
			</div>
		{% endfor %}

		<button type="submit" class="btn btn-success">Confirm changes</button>
	
	</form>
	
</div>
	{% include 'manager/structure/base_tpl_bottom.html' %}

manager/templates/manager/editcustomer.html

<!-- Basic HTML stuff (title, head, beginning of body) -->
{% include 'manager/structure/base_tpl_top.html' %}
<!-- Navigation -->
{% include 'manager/structure/navbar.html' %}

<div class="container">
	<h2>Edit customer {{ customer.name }}</h2>
	{% if error_message %} 
		<div class="alert alert-danger">{{ error_message }}</div>
	{% endif %}
	<form action="" method="post" role="form">
		{% csrf_token %}
		{% for field in form %}
			<div class="form-group">
				{{ field.errors }}
	            {{ field.label_tag }} {{ field }}
			</div>
		{% endfor %}
		<button type="submit" class="btn btn-success">Confirm changes</button>
	</form>


</div>

manager/templates/manager/index.html

	<!-- Basic HTML stuff (title, head, beginning of body) -->
	{% include 'manager/structure/base_tpl_top.html' %}
	<!-- Navigation -->
	{% include 'manager/structure/navbar.html' %}

	
	
	
	
	
	
	
	
	{% include 'manager/structure/base_tpl_bottom.html' %}

manager/templates/manager/login.html
{% include 'manager/structure/base_tpl_top.html' %}
{% load staticfiles %}
<link href="{% static 'manager/bootstrap/css/signin.css' %}" rel="stylesheet">
{% if error_message %} <p><strong>{{ error_message }}</strong></p> {% endif %}
<div class="container">
	<form class="form-signin" action="{% url 'manager:login_handle' %}" method="post">
	{% csrf_token %}
		<h2 class="form-signin-heading">Please sign in</h2>
		<input class="form-control" type="text" name="username" placeholder="Username" required autofocus />
		<input class="form-control" type="password" name="password" placeholder="Password" required/>
		<button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
	</form>
</div>
{% include 'manager/structure/base_tpl_bottom.html' %}

manager/templates/manager/newcontact.html

<!-- Basic HTML stuff (title, head, beginning of body) -->
{% include 'manager/structure/base_tpl_top.html' %}
<!-- Navigation -->
{% include 'manager/structure/navbar.html' %}

<div class="container">
	<h1>Add new contact</h1>
	{% if error_message %}
		<div class="alert alert-danger">{{ error_message }}</div>
	{% endif %}
	<form action="" method="post" role="form">
		{% csrf_token %} 
		{% for field in form %}
			<div class="form-group">
				{{ field.errors }}
	            {{ field.label_tag }} {{ field }}
			</div>
		{% endfor %}

		<button type="submit" class="btn btn-success">Add</button>
	
	</form>
</div>

manager/templates/manager/newcustomer.html

	<!-- Basic HTML stuff (title, head, beginning of body) -->
	{% include 'manager/structure/base_tpl_top.html' %}
	<!-- Navigation -->
	{% include 'manager/structure/navbar.html' %}

<div class="container">	
	<h1>Add new customer</h1>
	{% if error_message %} 
		<div class="alert alert-danger">{{ error_message }}</div>
	{% endif %}
	<form action="" method="post" role="form">
	{% csrf_token %}
	{% for field in form %}
		<div class="form-group">
			{{ field.errors }}
            {{ field.label_tag }} {{ field }}
		</div>
	{% endfor %}
	<button type="submit" class="btn btn-success">Add</button>
	</form>
	
</div>
	{% include 'manager/structure/base_tpl_bottom.html' %}